apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonserver-depl
spec:
  selector:
    matchLabels:
      app: jsonserver
  
  template:
    metadata:
      labels:
        app: jsonserver
    spec:
      containers:
      - name: jsonserver
        image: diaslinoh/json-server
        ports:
        - containerPort: 80
  
---

apiVersion: v1
kind: Service
metadata:
  name: jsonserver-service
spec:
  selector:
    app: jsonserver
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30099