apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlpad-depl
spec:
  selector:
    matchLabels:
      app: sqlpad
  template:
    metadata:
      labels:
        app: sqlpad
    spec:
      containers:
      - name: sqlpad
        image: sqlpad/sqlpad
        env:
          - name: SQLPAD_ADMIN
            value: admin@admin.com
          - name: SQLPAD_ADMIN_PASSWORD
            value: admin
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: sqlpad-service
spec:
  selector:
    app: sqlpad
  type: LoadBalancer
  ports:
  - port: 8989
    targetPort: 3000
    nodePort: 30010

